### ISSUE TITLE
Add firebase

### ISSUE THREAD

**Issue by hellodeborahuk** [hellodeborahuk/coding-notebook#1]
### Tasks

- [ ] Install firebase
- [ ] Save data to database
- [ ] Delete data from database
- [ ] Retrieve data from database
- [ ] Update data when editing

**Comment by KendallDoesCoding** [comment]
> 

This will be via the account system in #3 right? Or will it save anyones notes to your firebase for you to see?

**Comment by hellodeborahuk** [comment]
> > 
> 
> This will be via the account system in #3 right? Or will it save anyones notes to your firebase for you to see?

Yes I think so. I've not used Firebase properly before so it's all new to me. I'll learn as I go along.

**Comment by KendallDoesCoding** [comment]
Ok cool!
